<!-- application/layouts/scripts/logo.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  </head>
  <body>
    <div id="dLogoEsquerda">
      <img src="<?php echo $this->baseUrl('images/logo/logo128x384.png') ?>">
    </div>
    <div id="dLogoCentro">
      <table id="tLogoCentro">
        <tr>
          <td class="tdSocial">
            <a href="http://www.plus.google.com">
              <img src="<?php echo $this->baseUrl('images/24x24/social_blackGplus.png') ?>"></a>
          </td>
          <td class="tdSocial">
            <a href="http://www.facebook.com.br">
              <img src="<?php echo $this->baseUrl('images/24x24/social_blackFacebook1.png') ?>"></a>
          </td>
          <td class="tdSocial">
            <a href="http://www.twitter.com">
              <img src="<?php echo $this->baseUrl('images/24x24/social_blackTwitter1.png') ?>"></a>
          </td>
          <td class="tdSocial">
            <a href="http://www.instagram.com">
              <img src="<?php echo $this->baseUrl('images/24x24/social_blackInstagram.png') ?>"></a>
          </td>
          <td class="tdSocial">
            <a href="http://www.linkedin.com">
              <img src="<?php echo $this->baseUrl('images/24x24/social_blackLinkedin.png') ?>"></a>
          </td>
          <td class="tdSocial">
            <a href="http://www.skype.com">
              <img src="<?php echo $this->baseUrl('images/24x24/social_blackSkype.png') ?>"></a>
          </td>
          <td class="tdSocial">
            <a href="http://www.tumblr.com">
              <img src="<?php echo $this->baseUrl('images/24x24/social_blackTumblr.png') ?>"></a>
          </td>
          <td class="tdSocial">
            <a href="http://www.youtube.com.br">
              <img src="<?php echo $this->baseUrl('images/24x24/social_blackYoutube.png') ?>"></a>
          </td>
        </tr>
      </table>
    </div>
    <div id="dLogodDireita">
    </div>
  </body>
</html>